
FIND_PATH(VORBISENC_INCLUDE_DIR vorbis/vorbisenc.h /usr/include /usr/local/include)
FIND_LIBRARY(VORBISENC_LIBRARY NAMES vorbisenc PATH /usr/lib /usr/local/lib)

IF (VORBISENC_INCLUDE_DIR AND VORBISENC_LIBRARY)
	SET(VORBISENC_FOUND TRUE)
ENDIF (VORBISENC_INCLUDE_DIR AND VORBISENC_LIBRARY)

IF (VORBISENC_FOUND)
	IF (NOT vorbisenc_FIND_QUIETLY)
		MESSAGE(STATUS "Found vorbisenc: ${VORBISENC_INCLUDE_DIR}/vorbis/vorbisenc.h ${VORBISENC_LIBRARY}")
	ENDIF (NOT vorbisenc_FIND_QUIETLY)
ELSE (VORBISENC_FOUND)
	IF (vorbisenc_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find vorbisenc")
	ENDIF (vorbisenc_FIND_REQUIRED)
ENDIF (VORBISENC_FOUND)

