
FIND_PATH(ID3_INCLUDE_DIR id3/tag.h /usr/include /usr/local/include)
FIND_LIBRARY(ID3_LIBRARY NAMES id3 PATH /usr/lib /usr/local/lib)

IF (ID3_INCLUDE_DIR AND ID3_LIBRARY)
	SET(ID3_FOUND TRUE)
ENDIF (ID3_INCLUDE_DIR AND ID3_LIBRARY)

IF (ID3_FOUND)
	IF (NOT id3_FIND_QUIETLY)
		MESSAGE(STATUS "Found id3: ${ID3_INCLUDE_DIR}/id3/tag.h ${ID3_LIBRARY}")
	ENDIF (NOT id3_FIND_QUIETLY)
ELSE (ID3_FOUND)
	IF (id3_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find id3")
	ENDIF (id3_FIND_REQUIRED)
ENDIF (ID3_FOUND)

