
FIND_PATH(VORBISENC_INCLUDE_DIR vorbis/vorbisenc.h /usr/include /usr/local/include)
FIND_LIBRARY(OGG_LIBRARY NAMES ogg PATH /usr/lib /usr/local/lib)
FIND_LIBRARY(VORBIS_LIBRARY NAMES vorbis PATH /usr/lib /usr/local/lib)
FIND_LIBRARY(VORBISENC_LIBRARY NAMES vorbisenc PATH /usr/lib /usr/local/lib)

IF (VORBISENC_INCLUDE_DIR AND OGG_LIBRARY AND VORBIS_LIBRARY AND VORBISENC_LIBRARY)
	SET(VORBISENC_FOUND TRUE)
ENDIF (VORBISENC_INCLUDE_DIR AND OGG_LIBRARY AND VORBIS_LIBRARY AND VORBISENC_LIBRARY)

IF (VORBISENC_FOUND)
	IF (NOT vorbisenc_FIND_QUIETLY)
		MESSAGE(STATUS "Found vorbisenc: ${VORBISENC_INCLUDE_DIR}/vorbis/vorbisenc.h ${OGG_LIBRARY} ${VORBIS_LIBRARY} ${VORBISENC_LIBRARY}")
	ENDIF (NOT vorbisenc_FIND_QUIETLY)
ELSE (VORBISENC_FOUND)
	IF (vorbisenc_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find ogg, vorbis or vorbisenc")
	ENDIF (vorbisenc_FIND_REQUIRED)
ENDIF (VORBISENC_FOUND)

