#!/bin/sh

# this script creates version.cpp containing version and other compile-time
# information.  it expects to get the source directory as only argument.

output=version.cpp

src=$1
test "$src" = '' && src=.

date=`date --utc +%Y-%m-%d`
commit=`( cd "$src"; git rev-parse HEAD 2> /dev/null; )`
if test "$commit" != ''; then
	( cd "$src"; git diff --quiet HEAD; ) || commit="$commit-dirty"
else
	commit=unknown
fi
cat > "$output-new" <<EOF
#include "common.h"
const char *recorderCommit = "$commit";
const char *recorderDate = "$date";
EOF

if test -e "$output" && diff -q "$output" "$output-new" > /dev/null 2>&1; then
	rm "$output-new"
else
	mv "$output-new" "$output"
fi

