#!/bin/sh

v=''
scr=skype-call-recorder

while test $# != 0; do
	case "$1" in
		-*) echo "Unknown option $1" && exit 1 ;;
		*) v="$1" ;;
	esac
	shift
done

if test -z "$v"; then
	echo "Usage: $0 <version>"
	exit 1
fi

if git tag -l | grep -q "^$v\$" > /dev/null 2> /dev/null; then
	:
else
	echo "I don't know version $v, here's what I know:"
	git tag -l | sed -e 's/^/    /'
	exit 1
fi

export BASE=$(pwd)

tmp="$BASE/tmp-rpm-build"
rm -rf "$tmp" && \
mkdir "$tmp" && \
mkdir "$tmp"/SOURCES "$tmp"/BUILD "$tmp"/RPMS || exit 1

$BASE/utils/snapshot $v "$tmp/SOURCES/$scr-$v.tar.gz" || exit 1

git show -p $v:$scr.spec | sed -e "s/@version@/$v/g" > "$tmp/spec" || exit 1

rpmbuild -bb --define "_topdir $tmp" "$tmp/spec" || exit 1

mv "$tmp"/RPMS/*/* . || exit 1

rm -rf "$tmp"

