#!/bin/sh

target=ubuntu
version=''

while test $# != 0; do
	case "$1" in
		-e) target=eee ;;
		-u) target=ubuntu ;;
		-*) echo "Unknown option $1" && exit 1 ;;
		*) version="$1" ;;
	esac
	shift
done

if test -z "$version"; then
	echo "Usage: $0 [ -e | -u ] <version>"
	exit 1
fi

if git tag -l | grep -q "^$version\$" > /dev/null 2> /dev/null; then
	:
else
	echo "I don't know version $version, here's what I know:"
	git tag -l | sed -e 's/^/    /'
	exit 1
fi

export BASE=$(pwd)

if test $target = eee; then
	controlflags=eee
	cmake="$BASE/utils/cmake-static"
elif test $target = ubuntu; then
	controlflags=ubuntu
	cmake=cmake
else
	echo "Unknown target: $target"
	exit 1
fi

tmp=tmp-deb-build
rm -rf "$tmp"
mkdir "$tmp"

$BASE/utils/snapshot $version "$tmp/tarball.tar.gz" || exit 1
tar -xzf "$tmp/tarball.tar.gz" -C "$tmp"

(
	cd "$tmp/skype-call-recorder-$version"
	$cmake .
	make
	make DESTDIR=../root install
)

echo -n "Package size: "
size=`du -sk "$tmp/root" | cut -f1`
echo "$size KB"

echo -n "Generate control file: "

mkdir "$tmp/root/DEBIAN"
cp "$tmp/skype-call-recorder-$version/skype-call-recorder.control" "$tmp/root/DEBIAN/control"

for flag in $controlflags; do
	sed -i -e "s/^@@$flag\s\+//" "$tmp/root/DEBIAN/control"
done

sed -i \
	-e "/^#/d" \
	-e "/^@@\w\+\s/d" \
	-e "s/@version@/$version/g" \
	-e "s/@size@/$size/g" \
	"$tmp/root/DEBIAN/control"

arch=$(sed -ne 's/^Architecture: //p' "$tmp/root/DEBIAN/control")

echo Done

dpkg-deb -b -Zbzip2 -z9 "$tmp/root" "skype-call-recorder-${target}_${version}_$arch.deb"

rm -rf "$tmp"

