#!/bin/sh

if test "$1" = ''; then
	echo "Usage: $0 <tree-ish>"
	exit 1
fi

tree=$1

version=`git describe --tags "$tree" 2> /dev/null`

case "$version" in
	*-*|'')
		version=`date +%Y%m%d`
		;;
esac

base=skype-call-recorder-$version

if test "$2" != ''; then
	outfile=$2
else
	outfile=$base.tar.gz
fi

tmp="tmp.snapshot.$$"
rm -rf "$tmp"
mkdir "$tmp"

# we extract the archive, modify the directory and re-tar.  we do that because
# there's no simple way to add the gitcommit file under the right name using
# tar -A in a pipe.

git archive --format=tar --prefix="$base/" "$tree" | tar -x -C "$tmp"

rm -f "$tmp/$base/.gitignore"
rm -rf "$tmp/$base/utils/"{makedeb,snapshot}
git rev-parse "$tree" > "$tmp/$base/gitcommit"
git describe --tags "$tree" 2> /dev/null > "$tmp/$base/version" || cp "$tmp/$base/gitcommit" "$tmp/$base/version"
tar -C "$tmp" -c "$base" | gzip -9 > "$outfile"

rm -rf "$tmp"
echo "$outfile created"

