#!/bin/sh

gnuplot <<EOF

set xlabel "Time (mm:ss)"
set ylabel "Delay (s)"
set title "$1"
set xdata time
set timefmt "%s"
plot "$1" using (\$1/1000):(\$2/16000) with lines notitle, \
	"$1" using (\$1/1000):(\$3/16000) with lines notitle
pause mouse
exit

EOF

